//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeilGaiettoCom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageVisit
    {
        public int ID { get; set; }
        public string Page { get; set; }
        public string Visitor { get; set; }
        public System.DateTime When { get; set; }
    }
}
